treadmill-tb/treadmill

- .github/workflows/ci.yml
- rust-toolchain.toml
This checks that we're not merging anything that breaks formatting and/or compilation, easy enough.
It also adds a `rust-toolchain.toml` file that, for rustup users, ensures we're building on the stable toolchain and have the `rustfmt` component installed.
> Add basic GitHub actions CI to test compilation and formatting

- connector/cli/src/lib.rs
- treadmill-rs/Cargo.toml
- treadmill-rs/src/api/coord_supervisor.rs
- treadmill-rs/src/image/image_store.rs
- treadmill-rs/src/image/manifest.rs
- treadmill-rs/src/lib.rs
- treadmill-rs/src/util.rs
This specifies the base format of image manifests, and a file system layout for image stores (and local caches, which expose their store contents via a read-only shared filesystem).
We change the image identifier from a UUID to the image manifest's SHA256-digest. For now, we simply hard-code one arbitrary digest in the CLI connector.
This image manifest format is currently being used for the WIP QEMU supervisor component.
> Add initial Image Manifest specification

- supervisor/mock/src/main.rs
- treadmill-rs/src/connector.rs
The `job_id` is passed outside of the `JobError` struct (such as through the HTTP endpoint to which the `JobError` struct is posted).
> Remove unused job_id

- connector/cli/src/lib.rs
- puppet/src/control_socket_client.rs
- puppet/src/main.rs
- supervisor/mock/src/main.rs
- treadmill-rs/src/api/supervisor_puppet.rs
- treadmill-rs/src/api/switchboard_supervisor.rs
- treadmill-rs/src/control_socket.rs
This commit loops the job parameters HashMap through from the initial start job request to the supervisor, and then allows the puppet daemon to retrieve it. This daemon in turn can create a directory that exposes the contents of this map as a set of files.
> Forward job parameters from Coordinator via Supervisor to Puppet

- connector/cli/src/lib.rs
- control-socket/tcp/server/src/lib.rs
- puppet/src/control_socket_client.rs
- puppet/src/main.rs
- supervisor/mock/src/main.rs
- treadmill-rs/src/api/supervisor_puppet.rs
- treadmill-rs/src/api/switchboard_supervisor.rs
- treadmill-rs/src/control_socket.rs
Avoid us having to replicate this dispatch code in every Supervisor implementation.
Depends on #14.
> treadmill-rs: provide default handle_request impl for control_socket::Supervisor

- .github/workflows/ci.yml
- Cargo.lock
This adds `--locked` to `cargo build` in our CI workflow, which in turn ensures that the checked in `Cargo.lock` stays current.
The first commit does not update `Cargo.lock`, and as such fails CI:
```
cargo build --locked
shell: /usr/bin/bash -e {0}
env:
TERM: xterm
CARGO_INCREMENTAL: 0
CARGO_PROFILE_DEV_DEBUG: 0
CARGO_TERM_COLOR: always
RUST_BACKTRACE: short
RUSTFLAGS: -D warnings
CARGO_UNSTABLE_SPARSE_REGISTRY: true
CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
CACHE_ON_FAILURE: true
error: the lock file /home/runner/work/treadmill/treadmill/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
Error: Process completed with exit code 101.
``` …
> ci-build: check that lockfile is current

- Cargo.lock
- Cargo.toml
- control-socket/tcp/server/src/lib.rs
- supervisor/qemu/.gitignore
- supervisor/qemu/Cargo.toml
- supervisor/qemu/config.example.toml
- supervisor/qemu/src/image_store_client.rs
- supervisor/qemu/src/main.rs
- treadmill-rs/Cargo.toml
- treadmill-rs/src/connector.rs
This adds an initial, work-in-progress QEMU supervisor to start virtual machine-backed jobs.
It contains more general logic for dealing with QCOW2 images, an initial image manifest file format specification, and scaffolding for an image store client. Those components may need to be split out into individual crates or the common `treadmill-rs` crate later.
The code in this commit is enough to be able to start and stop a virtual machine based on an image located in the image store, by using the connector API.
> Add QEMU Supervisor

- .sqlx/query-846747f9007cfa1faf02c7a595734be025f68079b8f71d70cd9e0f7e4d8565fd.json
- switchboard/switchboard/src/model/job.rs
Bugfix for CI issues noted in #36. Query was inserting all parameter keys paired with all parameter values (instead of all parameter keys, each with their own value), which created violations of the primary key constraint.
The query has been rewritten and tested.
As this was an issue at the SQL level that could not be caught anywhere higher, no additional validation has been added.
> dev/switchboard: Fix job parameter insertion SQL query.

- connector/ws/Cargo.toml
- connector/ws/src/lib.rs
This makes it easier to exclude secrets from otherwise public configuration files.
> connector/ws: allow reading token from file in addition to config

- Cargo.lock
- switchboard/switchboard/Cargo.toml
- switchboard/switchboard/config.example.toml
- switchboard/switchboard/src/cfg.rs
- switchboard/switchboard/src/server.rs
Add `server.tokio_console_server` configuration option.
Usage instructions:
- `cargo install tokio-console`
- build with `RUSTFLAGS="--cfg tokio_unstable"`
- run with `server.tokio_console_server = true`
- run `tokio-console`
By default, this will open the tokio-console server that binds to `127.0.0.1:6669`.
> switchboard: Add console-subscriber support

- switchboard/src/auth/db.rs
This partially addresses https://github.com/treadmill-tb/treadmill/issues/63 by creating an all-capable admin permission which we can assign to system administrators.
It also allows us to roll this system out among an initial set of fully trusted users while we are revisiting the permissions system.
> switchboard: add all-capable "admin" permission

- supervisor/qemu/src/main.rs
- Added a shutdown channel to allow for controlled termination of QEMU processes.
- Modified the `stop_job` method to send a shutdown signal instead of immediately killing the process.
- Implemented a new task that monitors each running QEMU process.
- This task waits for either process termination or a shutdown signal
- Implementation of a timeout mechanism for graceful shutdowns.
- Finalizing the WebSocket connection retry logic by changing `connector.run()`
>  Implement graceful shutdown and asynchronous monitoring for QEMU processes

- LICENSE-APACHE
- LICENSE-MIT
Applies the Apache-2.0 and MIT license to all code contained in this repository.
> Dual-license code under MIT and Apache-2.0

- Cargo.lock
- puppet/Cargo.toml
- puppet/src/control_socket_client.rs
- puppet/src/main.rs
- supervisor/mock/src/main.rs
- supervisor/qemu/src/main.rs
- treadmill-rs/src/api/supervisor_puppet.rs
- treadmill-rs/src/control_socket.rs
This adds a DBus interface to the Treadmill puppet binary, through which the host operating system (either directly through DBus or via the built-in commands in the Treadmill binary) can control this daemon.
The first command implemented is one to terminate the current job, required for hosts which do not have a main process that can be terminated from within the host (like netboot targets).
> Allow terminating job from within host through puppet

- .github/workflows/cli-tests.yml
- .github/workflows/e2e-tests.yml
- Cargo.lock
- cli/Cargo.toml
- connector/cli/Cargo.toml
- connector/ws/Cargo.toml
- control-socket/tcp/client/Cargo.toml
- control-socket/tcp/server/Cargo.toml
- puppet/Cargo.toml
- puppet/src/control_socket_client.rs
- supervisor/lib/Cargo.toml
- supervisor/mock/Cargo.toml
- supervisor/mock/src/main.rs
- supervisor/nbd-netboot/Cargo.toml
- supervisor/nbd-netboot/src/main.rs
- supervisor/qemu/Cargo.toml
- supervisor/qemu/src/main.rs
- switchboard/Cargo.toml
- switchboard/src/bin/swx.rs
We are about to publish an initial version of the Treadmill CLI client to crates.io. While the CLI client crate is named "tml-cli", the base-crate containing API and type definitions, which we have to publish alongside it, is called "treadmill-rs". The "tml-" prefix, while nice and short, is rather ambiguous. We should publish the crates prefixed with "treadmill-", and then produce binaries that are available under the shortened "tml" prefix (such as the CLI crate, which produces a binary named `tml`).
> Unify crate name prefix to "treadmill-"

- cli/Cargo.toml
- treadmill-rs/Cargo.toml
Adds the necessary metadata for publishing on crates.io, and adds a "package" dependency of `treadmill-cli` on `treadmill-rs`, next to the "path" dependency we use in this Cargo workspace.
> Prepare `treadmill-rs` and `treadmill-cli` crates for publishing on crates.io

- Cargo.lock
Upon trying to publish this crate, cargo showed the following warning:
warning: package `futures-util v0.3.30` in Cargo.lock is yanked in
registry `crates-io`, consider updating to a version that is not
yanked
Updating `treadmill-cli` dependencies fixed this issue. It still uses an outdated version of `clap`, which we update in a future revision.
> `cargo update` the treadmill-cli dependencies

- switchboard/Cargo.toml
- switchboard/src/service.rs
- switchboard/src/service/kanban.rs
By sorting the jobs returned by the Kanban service, the supervisor match daemon should start earlier jobs first. This ensures fairness during scheduling, and helps to avoid jobs racing against the queue timeout when there's a constant influx of new jobs being enqueued.
> switchboard: match jobs with supervisors in enqueue order

- shell.nix
Fixes the following warning when evaluating the shell.nix expression
on NixOS 24.11:
trace: evaluation warning: `rust.toRustTarget platform` is
deprecated. Use `platform.rust.rustcTarget` instead.
> Update fenix to fix warning on NixOS 24.11

- .github/workflows/cli-tests.yml
- .github/workflows/e2e-tests.yml
This should hopefully get rid of some CI errors, which presumably are because we're caching a binstall'ed version that uses a different dynamic loader path?
> GitHub Actions: force-reinstall sqlx-cli, even if cached

- control-socket/tcp/server/src/lib.rs
- puppet/src/control_socket_client.rs
- puppet/src/main.rs
- supervisor/mock/src/main.rs
- supervisor/nbd-netboot/src/main.rs
- supervisor/qemu/src/main.rs
- treadmill-rs/src/api/supervisor_puppet.rs
- treadmill-rs/src/control_socket.rs
This changes the `job_id_path` parameter to a `job_info_dir` parameter, such that general job metadata may be written to this directory without further command line parameter changes. As of now, this path will have `job-id` and `host-id` propagated, but further files / metadata may be added in the future (like a job label).
This PR raises the question: are the "host IDs" and "supervisor IDs" really synonymous? Right now, we treat them as such, but at the same time supervisors are written to potentially spawn multiple different jobs simultaneously, on multiple hosts (i.e., there may not always be a 1-to-1 correlation between supervisors and hosts).
It seems fine to assume that they are, and continue with the assumption that---for the time being---there is always a 1-to-1 mapping between …
> puppet: expose host-id as part of job info files

- connector/cli/src/lib.rs
- connector/ws/src/lib.rs
- supervisor/mock/src/main.rs
- supervisor/nbd-netboot/src/main.rs
- supervisor/qemu/src/main.rs
- treadmill-rs/src/connector.rs
- Adds a shutdown-requested flag to let the connector exit gracefully instead of killing in-progress jobs.  
- On SIGHUP, we set this flag, and the connector returns from `run()` once idle.  
- The main loop then exits, allowing systemd to restart the supervisor with new config/binaries without interrupting active jobs.
> Gracefully Shutdown Supervisors on SIGHUP for Config/Version Reload
